name: Run tests

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the type of virtual machine to use

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python tests/run_tests.py
